export const PARTNERS = [
  {
    id: 1,
    name: "Federal Road Safety Corps (FRSC)",
    description: "The FRSC is mandated to create safe roads and monitor accidents in Nigeria. They partnered with HEI to provide emergency medical attention to road traffic accident victims.",
    website: "https://frsc.gov.ng/",
    logo: "/partners/FRSC.png",
  },
  {
    id: 2,
    name: "Lagos State Ambulance Service (LASAMBUS)",
    description: "Launched in 2001 to provide pre-hospital care services during medical emergencies. LASAMBUS partnered with HEI to offer immediate healthcare support during emergencies across Lagos State.",
    website: "https://health.lagosstate.gov.ng/",
    logo: "/partners/Lasambus.jpg",
  },
  {
    id: 3,
    name: "Lagos State Ministry of Health",
    description: "HEI partners with federal hospitals in Lagos — including LUTH, National Orthopaedic Igbobi, and Federal Medical Centre Ebutte Metta — and over 25 state hospitals, to provide emergency healthcare assistance.",
    website: "https://health.lagosstate.gov.ng/",
    logo: "/partners/Lagos-State-Government-768x431.jpg",
  },
  {
    id: 4,
    name: "PricewaterhouseCoopers (PwC)",
    description: "PwC is among the leading professional services networks in the world, helping organisations and individuals deliver quality in assurance, tax, and advisory services.",
    website: "https://www.pwc.com/ng/en.html",
    logo: "/partners/09-pwc.jpg",
  },
  {
    id: 5,
    name: "Microsoft",
    description: "Microsoft is a global technology leader empowering individuals and organisations through innovative software, cloud services, AI, and digital solutions that transform how people work, learn, and connect.",
    website: "https://www.microsoft.com/en-ng",
    logo: "/partners/microsoft_logo.png",
  },
  {
    id: 6,
    name: "UPS Foundation",
    description: "The UPS Foundation is dedicated to building stronger, safer, more resilient, and inclusive communities around the world through strategic philanthropy and global partnerships.",
    website: "https://about.ups.com/us/en/social-impact/the-ups-foundation.html",
    logo: "/partners/ups-1.jpg",
  },
  {
    id: 7,
    name: "Sterling Bank Plc",
    description: "Sterling Bank Plc is a full-service national commercial bank in Nigeria. Over 50 years of operations, it has evolved into a fully-fledged bank committed to innovative financial solutions and community development.",
    website: "https://sterling.ng/",
    logo: "/partners/sterling.jpeg",
  },
  {
    id: 8,
    name: "Woodhall Capital Foundation",
    description: "Woodhall Capital Foundation focuses on working with local communities to create a better quality of life for the underserved through education empowerment and access to food.",
    website: "https://woodhallcapfoundation.org/",
    logo: "/partners/wcf.jpg",
  },
  {
    id: 9,
    name: "Digital Marketing Skills Institute",
    description: "A digital marketing company focused on customers' success and building the industry's highest-quality training and consulting products delivered with high standards.",
    website: "https://dmsinstitute.com/",
    logo: "/partners/dmsi2.png",
  },
  {
    id: 10,
    name: "MultiChoice Nigeria (DSTV)",
    description: "DSTV is Africa's leading entertainment company, creating and securing rights to phenomenal content delivered through Direct To Home (DTH), Digital Terrestrial Television, and online video entertainment.",
    website: "https://www.multichoice.com/",
    logo: "/partners/multichoice.png",
  },
  {
    id: 11,
    name: "Spectranet",
    description: "Spectranet was awarded a licence from the Nigerian Communications Commission in 2009. It was the first ISP to launch 4G LTE internet service in Nigeria, aiming to be a leader in the internet services space.",
    website: "https://spectranet.com.ng/",
    logo: "/partners/spect.jpg",
  },
  {
    id: 12,
    name: "Verraki",
    description: "Verraki is a proudly African business solutions firm that builds technology solutions for complex challenges and curates innovative ventures to unlock new sources of growth across the continent.",
    website: "https://verraki.africa/",
    logo: "/partners/verraki_600.jpg",
  },
  {
    id: 13,
    name: "Rotary Club of Victoria Island",
    description: "The Rotary Club of Victoria Island Lagos brings together professionals and community leaders committed to addressing local and global challenges, supporting educational initiatives, and improving lives in Lagos.",
    website: "https://www.rotary.org/",
    logo: "/partners/rotary_club_vi.jpg",
  },
  {
    id: 14,
    name: "Sterling One Foundation",
    description: "Sterling One Foundation is a leading social impact organisation driving progressive change across Africa through targeted interventions in education, youth development, health programs, and climate action.",
    website: "https://onefoundation.ng/",
    logo: "/partners/one_foundation.png",
  },
  {
    id: 15,
    name: "CardGoal",
    description: "CardGoal is an all-in-one digital trading and payment platform designed to simplify everyday financial transactions — from gift cards and airtime to paying bills — through a single user-friendly app.",
    website: "https://cardgoal.com/",
    logo: "/partners/cardgoal.png",
  },
  {
    id: 16,
    name: "LFR International",
    description: "LFR International is a non-profit research and capacity-building organisation dedicated to empowering lay first responders in resource-limited communities worldwide, helping prevent needless loss of life.",
    website: "https://lfrinternational.org/",
    logo: "/partners/lfr-int.png",
  },
  {
    id: 17,
    name: "Continental Logistics Limited (CIL)",
    description: "Continental Logistics Limited (CIL) was incorporated in Nigeria in March 2004 as a private limited liability company and premier 4th Party Supply Chain Services Provider.",
    website: "https://cll-ng.com/",
    logo: "/partners/CL.png",
  },
  {
    id: 18,
    name: "IshK Tolaram Foundation",
    description: "IshK Tolaram Foundation is a nonprofit organisation committed to providing quality education, healthcare, and skills training to underserved individuals within their core geographies.",
    website: "https://ishktolaram.org/",
    logo: "/partners/tolaram.png",
  },
  {
    id: 19,
    name: "Lagos State Safety Commission",
    description: "The Lagos State Safety Commission coordinates all Government matters relating to the safety of lives and property of Lagosians, formulating policies, providing advisory, and serving as the regulatory body on safety issues.",
    website: "https://lasgsafety.com/",
    logo: "/partners/lassc-logo.png",
  },
  {
    id: 20,
    name: "First E&P",
    description: "First E&P was established in 2011 as a leading integrated energy company delivering end-to-end solutions across the upstream oil and gas value chain, from drilling and well completion to testing and production.",
    website: "https://www.first-epdc.com/",
    logo: "/partners/First-EP.png",
  },
  {
    id: 21,
    name: "REAN Foundation",
    description: "REAN Foundation delivers innovative healthcare solutions to remote populations, empowering patients with affordable, at-home self-management tools and secure, customised support in local languages for underserved communities.",
    website: "https://www.reanfoundation.org/",
    logo: "/partners/REAN-Foundation.png",
  },
  {
    id: 22,
    name: "Healthcare Federation of Nigeria (HFN)",
    description: "HFN is transforming healthcare advocacy in Nigeria, launching a refined digital platform to better connect and serve its members and stakeholders across the country.",
    website: "https://hfnigeria.com/",
    logo: "/partners/HCFLogo.png",
  },
  {
    id: 23,
    name: "Lagos University Teaching Hospital (LUTH)",
    description: "LUTH is Nigeria's leading tertiary hospital, operating across Yaba and Pakoto with over 960 beds and 46 clinical departments. A team of over 2,000 professionals delivers comprehensive, world-class healthcare.",
    website: "https://luth.org.ng/",
    logo: "/partners/luth-logo.jpg",
  },
  {
    id: 24,
    name: "TotalEnergies",
    description: "TotalEnergies is a global multi-energy company that produces and markets energies on a global scale including oil and natural gas, renewables, and electricity.",
    website: "https://totalenergies.ng/",
    logo: "/partners/totalenergies.png",
  },
  {
    id: 25,
    name: "Nigerian Exchange Group (NGX)",
    description: "NGX is the premier stock exchange and market infrastructure provider in Nigeria, facilitating the trading of equities, bonds, and financial instruments while driving capital formation and economic growth.",
    website: "https://ngxgroup.com/",
    logo: "/partners/Nigerian-Exchange-Group-Logo-1.png",
  },
  {
    id: 26,
    name: "The M. Kukoyi Foundation (MKF)",
    description: "MKF is a nonprofit organisation dedicated to bridging the gap in health outcomes and educational opportunities in underserved communities across Africa, optimising healthcare delivery and fostering youth development.",
    website: "https://themkfoundation.com/",
    logo: "/partners/mkukoyi-foundation.png",
  },
  {
    id: 27,
    name: "Ashoka",
    description: "Ashoka is a global leader in social innovation, building a future where everyone has the power to shape society's most pressing challenges by empowering changemakers to create lasting positive impact worldwide.",
    website: "https://www.ashoka.org/en-ng",
    logo: "/partners/ashoka.png",
  },
  {
    id: 28,
    name: "U.S. Mission to Nigeria",
    description: "The U.S. Mission to Nigeria is the official diplomatic presence of the United States government in Nigeria, comprising the U.S. Embassy in Lagos and consulates across the country.",
    website: "https://ng.usembassy.gov/",
    logo: "/partners/united-state-mission.png",
  },
  {
    id: 29,
    name: "Seplat Energy",
    description: "Seplat Energy is committed to delivering sustainable energy solutions, focusing on responsible exploration, production, and monetisation of hydrocarbon resources while investing in the energy transition and community well-being.",
    website: "https://www.seplatenergy.com/",
    logo: "/partners/Seplat-Energy.png",
  },
  {
    id: 30,
    name: "Google",
    description: "Google is a global technology company delivering innovative products and services spanning search, cloud computing, AI, digital advertising, and consumer technology that transform how people access information worldwide.",
    website: "https://google.com",
    logo: "/partners/google_img.png",
  },
  {
    id: 31,
    name: "KPMG Nigeria",
    description: "KPMG is one of the leading global networks of professional services firms, delivering a comprehensive range of audit, tax, and advisory services to help organisations navigate complex business challenges.",
    website: "https://kpmg.com/ng/en/home.html",
    logo: "/partners/kpmg.png",
  },
  {
    id: 32,
    name: "The Metropolitan Club, Lagos",
    description: "Founded in 1960, The Metropolitan Club is a prestigious historic social club that brings together Nigeria's finest professionals, business leaders, academics, diplomats, and public officers.",
    website: "https://www.metclub.ng/",
    logo: "/partners/metropoliticanclub.png",
  },
];
